// Generated by gencpp from file lidar_ros/Path.msg
// DO NOT EDIT!


#ifndef LIDAR_ROS_MESSAGE_PATH_H
#define LIDAR_ROS_MESSAGE_PATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <lidar_ros/PathPoint.h>

namespace lidar_ros
{
template <class ContainerAllocator>
struct Path_
{
  typedef Path_<ContainerAllocator> Type;

  Path_()
    : points()  {
    }
  Path_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::lidar_ros::PathPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::lidar_ros::PathPoint_<ContainerAllocator> >> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::lidar_ros::Path_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_ros::Path_<ContainerAllocator> const> ConstPtr;

}; // struct Path_

typedef ::lidar_ros::Path_<std::allocator<void> > Path;

typedef boost::shared_ptr< ::lidar_ros::Path > PathPtr;
typedef boost::shared_ptr< ::lidar_ros::Path const> PathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_ros::Path_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_ros::Path_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lidar_ros::Path_<ContainerAllocator1> & lhs, const ::lidar_ros::Path_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lidar_ros::Path_<ContainerAllocator1> & lhs, const ::lidar_ros::Path_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lidar_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lidar_ros::Path_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_ros::Path_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_ros::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_ros::Path_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_ros::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_ros::Path_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_ros::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "70cf4eb62ba8e9c3eea820af04c7d4fd";
  }

  static const char* value(const ::lidar_ros::Path_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x70cf4eb62ba8e9c3ULL;
  static const uint64_t static_value2 = 0xeea820af04c7d4fdULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_ros::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_ros/Path";
  }

  static const char* value(const ::lidar_ros::Path_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_ros::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 路径\n"
"\n"
"PathPoint[] points  # 路径采样点\n"
"\n"
"================================================================================\n"
"MSG: lidar_ros/PathPoint\n"
"# 路径点(无曲率)\n"
"\n"
"float32 x  # x坐标\n"
"float32 y  # y坐标\n"
"float32 l # y坐标\n"
"float32 r  # y坐标\n"
"float32 s  # y坐标\n"
"float32 heading  # y坐标\n"
"float32 kappa  # y坐标\n"
;
  }

  static const char* value(const ::lidar_ros::Path_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_ros::Path_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Path_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_ros::Path_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_ros::Path_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::lidar_ros::PathPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_ROS_MESSAGE_PATH_H
