// Generated by gencpp from file lidar_ros/PathPoint.msg
// DO NOT EDIT!


#ifndef LIDAR_ROS_MESSAGE_PATHPOINT_H
#define LIDAR_ROS_MESSAGE_PATHPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lidar_ros
{
template <class ContainerAllocator>
struct PathPoint_
{
  typedef PathPoint_<ContainerAllocator> Type;

  PathPoint_()
    : x(0.0)
    , y(0.0)
    , l(0.0)
    , r(0.0)
    , s(0.0)
    , heading(0.0)
    , kappa(0.0)  {
    }
  PathPoint_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , l(0.0)
    , r(0.0)
    , s(0.0)
    , heading(0.0)
    , kappa(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _l_type;
  _l_type l;

   typedef float _r_type;
  _r_type r;

   typedef float _s_type;
  _s_type s;

   typedef float _heading_type;
  _heading_type heading;

   typedef float _kappa_type;
  _kappa_type kappa;





  typedef boost::shared_ptr< ::lidar_ros::PathPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_ros::PathPoint_<ContainerAllocator> const> ConstPtr;

}; // struct PathPoint_

typedef ::lidar_ros::PathPoint_<std::allocator<void> > PathPoint;

typedef boost::shared_ptr< ::lidar_ros::PathPoint > PathPointPtr;
typedef boost::shared_ptr< ::lidar_ros::PathPoint const> PathPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_ros::PathPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_ros::PathPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lidar_ros::PathPoint_<ContainerAllocator1> & lhs, const ::lidar_ros::PathPoint_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.l == rhs.l &&
    lhs.r == rhs.r &&
    lhs.s == rhs.s &&
    lhs.heading == rhs.heading &&
    lhs.kappa == rhs.kappa;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lidar_ros::PathPoint_<ContainerAllocator1> & lhs, const ::lidar_ros::PathPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lidar_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lidar_ros::PathPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_ros::PathPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_ros::PathPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_ros::PathPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_ros::PathPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_ros::PathPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_ros::PathPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d591e32f6fe60e3e01a68d4d5db745e";
  }

  static const char* value(const ::lidar_ros::PathPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d591e32f6fe60e3ULL;
  static const uint64_t static_value2 = 0xe01a68d4d5db745eULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_ros::PathPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_ros/PathPoint";
  }

  static const char* value(const ::lidar_ros::PathPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_ros::PathPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 路径点(无曲率)\n"
"\n"
"float32 x  # x坐标\n"
"float32 y  # y坐标\n"
"float32 l # y坐标\n"
"float32 r  # y坐标\n"
"float32 s  # y坐标\n"
"float32 heading  # y坐标\n"
"float32 kappa  # y坐标\n"
;
  }

  static const char* value(const ::lidar_ros::PathPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_ros::PathPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.l);
      stream.next(m.r);
      stream.next(m.s);
      stream.next(m.heading);
      stream.next(m.kappa);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_ros::PathPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_ros::PathPoint_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "l: ";
    Printer<float>::stream(s, indent + "  ", v.l);
    s << indent << "r: ";
    Printer<float>::stream(s, indent + "  ", v.r);
    s << indent << "s: ";
    Printer<float>::stream(s, indent + "  ", v.s);
    s << indent << "heading: ";
    Printer<float>::stream(s, indent + "  ", v.heading);
    s << indent << "kappa: ";
    Printer<float>::stream(s, indent + "  ", v.kappa);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_ROS_MESSAGE_PATHPOINT_H
